.\" @(#)alienfx.1 0.1 2010-11-01 Talisman
.ds p alienfx-uptime
.TH alienfx 1 "2010-11-01" "Group Talisman" "Talisman Utilities"
.SH NAME
alienfx-uptime \- visualize system load using the AlienFX device.
.SH SYNOPSIS
.LP
.B \*p
.SH DESCRIPTION
.LP
.B \*p
is a utility for visualizing the current system load average (specifically
the one-minute average as shown by \fBuptime(1)\fP)
via the AlienWare AlienFX LED case lighting system
as seen on the Aurora line, generally sold by Dell.
.SH COPYRIGHT
.IP "Copyright (c) 2010 C. Alex. North-Keys"
.PP
.B \*p
is distributed under the terms of the GNU General Public License.
See http://www.gnu.org/licenses/ for complete information.
.PP
This software is provided "as is", with no warranty, guarantee, support,
maintenance, update schedule, claims to fitness for any purpose, or
anything else from the author or any other physical or legal entity.
.SH "SEE ALSO"
.BR alienfx (1)
